apiVersion: v1
kind: ConfigMap
metadata:
  name: synthetic-check-script
data:
  check.sh: |
    #!/bin/sh
    set -e
    
    echo "Running synthetic checks..."
    
    # Check main endpoint
    echo "Testing / endpoint..."
    response=$(curl -w "\n%{http_code}" -sS http://app.prod.svc.cluster.local/)
    status=$(echo "$response" | tail -n1)
    body=$(echo "$response" | sed '$d')
    
    if [ "$status" != "200" ]; then
      echo "ERROR: / returned status $status"
      exit 1
    fi
    
    # Just verify we got a response body
    if [ -z "$body" ]; then
      echo "ERROR: Empty response body"
      exit 1
    fi
    
    echo "All synthetic checks passed!"
    exit 0