apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app
  labels:
    app: app
spec:
  selector:
    matchLabels:
      app: app
  endpoints:
    - port: http
      interval: 30s
      path: /metrics