apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-global
  labels:
    monitoring: prometheus
spec:
  selector:
    matchLabels:
      app: app
  namespaceSelector:
    matchNames:
      - dev
      - prod
  endpoints:
    - port: http
      interval: 30s
      path: /metrics